package com.fpnatools.aggregation.insurances.framework.restAPI.enums;

public enum InsuranceType {
	SAVING_INSURANCE, LIFE_INSURANCE, HEALTH_INSURANCE, PROPERTY_INSURANCE, 
		TRAVEL_INSURANCE, DEATH_INSURANCE, ACCIDENT_INSURANCE, CAR_INSURANCE,
		CIVIL_LIABILITY_INSURANCE

}