spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aggregation_insurances
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9091/oauth2/jwks
  

server:
  port: 9090
  
selenium:
  grid:
    url: http://localhost:4444
