spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aggregation_insurances
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9091/oauth2/jwks
  

server:
  port: 9090
  shutdown: graceful
  
selenium:
  grid:
    url: http://localhost:4444
    
certificates:
  path: ./config/keystores
