apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: insurances-aggregation
    env: dev
  name: insurances-aggregation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurances-aggregation
      env: dev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: insurances-aggregation
        env: dev
    spec:
      containers:
      - image: actraiser/insurances-aggregation:1.0.0
        name: insurances-aggregation
        imagePullPolicy: Always
        envFrom: 
          - configMapRef:
              name: insurances-aggregation-cm
            
status: {}
