apiVersion: batch/v1
kind: CronJob
metadata:
  name: insurances-aggregation-cronjob
  labels:
    app: insurances-aggregation
    env: dev
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: insurances-aggregation-job
              image: ubuntu:20.04
              command: ["/bin/bash", "-c"]
              args: ["curl http://insurances-aggregation:9090/executions/echo"]