name: Deploy cluster kubernetes
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: set-context
        uses: azure/k8s-set-context@v1
        with:
          k8s-secret: ${{ secrets.DIGITALOCEAN_TOKEN }}
          k8s-url: https://115f9fa6-df7d-40ba-910d-1dcc2c6d9c72.k8s.ondigitalocean.com
          method: service-account
      - name: list pods
        run: kubectl get pods
