name: Deploy cluster kubernetes
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: set-context
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.DIGITALOCEAN_KUBECONFIG }}
          context: do-fra1-cluster-josemi
      - name: list pods
        run: kubectl get pods
